/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/components/Item/AddItem.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DeleteItem: typeof import('./src/components/Item/DeleteItem.vue')['default']
    ItemDetail: typeof import('./src/components/Item/ItemDetail.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/Item/SearchForm.vue')['default']
    TextAreaInput: typeof import('./src/components/TextAreaInput.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
  }
}
